imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'bootstrap_3_layout.html.twig'
        - ':Form:theme.html.twig'
        - 'EntityModalBundle:EntityModal:form_theme.html.twig'

assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]

    filters:
        cssrewrite: ~
    assets:
        jquery:
            inputs:
                - %kernel.root_dir%/../vendor/components/jquery/jquery.min.js
        jqueryui:
            inputs:
                - %kernel.root_dir%/../vendor/components/jqueryui/jquery-ui.min.js

        bootstrap_js:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/js/bootstrap.js
        bootstrap_css:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap.css
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap-theme.css
            filters: [cssrewrite]

        bootstrap_css_map:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap.css.map
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap-theme.css.map
            output: "css/bootstrap.css.map"

        bootstrap_glyphicons_ttf:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf
            output: "fonts/glyphicons-halflings-regular.ttf"
        bootstrap_glyphicons_eot:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.eot
            output: "fonts/glyphicons-halflings-regular.eot"
        bootstrap_glyphicons_svg:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.svg
            output: "fonts/glyphicons-halflings-regular.svg"
        bootstrap_glyphicons_woff:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.woff
            output: "fonts/glyphicons-halflings-regular.woff"
        bootstrap_glyphicons_woff2:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2
            output: "fonts/glyphicons-halflings-regular.woff2"

        fontawesome:
            inputs:
                - '%kernel.root_dir%/../vendor/components/font-awesome/css/font-awesome.css'
        fontawesome-woff:
            inputs:
                - %kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.woff
            output: "fonts/fontawesome-webfont.woff"
        fontawesome-woff2:
            inputs:
                - %kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.woff2
            output: "fonts/fontawesome-webfont.woff2"

        adminlte_js:
            inputs:
                - '%kernel.root_dir%/../vendor/almasaeed2010/adminlte/dist/js/app.js'
        adminlte_css:
            inputs:
                - '%kernel.root_dir%/../vendor/almasaeed2010/adminlte/dist/css/AdminLTE.css'
                - '%kernel.root_dir%/../vendor/almasaeed2010/adminlte/dist/css/skins/skin-blue.css'

        datatables_js:
            inputs:
                - '%kernel.root_dir%/../vendor/almasaeed2010/adminlte/plugins/datatables/jquery.dataTables.min.js'
        datatables_js2:
            inputs:
                - '%kernel.root_dir%/../vendor/almasaeed2010/adminlte/plugins/datatables/dataTables.bootstrap.min.js'
        datatables_css:
            inputs:
                - '%kernel.root_dir%/../vendor/almasaeed2010/adminlte/plugins/datatables/dataTables.bootstrap.css'

        treegrid_js:
            inputs:
                - %kernel.root_dir%/../vendor/maxazan/jquery-treegrid/js/jquery.treegrid.js
                - %kernel.root_dir%/../vendor/maxazan/jquery-treegrid/js/jquery.treegrid.bootstrap3.js
        treegrid_css:
            inputs:
                - %kernel.root_dir%/../vendor/maxazan/jquery-treegrid/css/jquery.treegrid.css

        entitymodal_js:
            inputs:
                - %kernel.root_dir%/../vendor/xaifiet/entity-modal/Resources/public/js/entity_modal.js

        entitymodal_css:
            inputs:
                - %kernel.root_dir%/../vendor/xaifiet/entity-modal/Resources/public/css/entity_modal.css

        jquerybind_js:
            inputs:
                - %kernel.root_dir%/../vendor/xaifiet/jquery-bind/jquery-bind.min.js

        passvault_js:
            inputs:
                - %kernel.root_dir%/../src/PassVault/PassBundle/Resources/public/js/passvault.js

        passvault_css:
            inputs:
                - %kernel.root_dir%/../src/PassVault/PassBundle/Resources/public/css/passvault.css


# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
  db_driver: orm
  firewall_name: secured_area
  user_class: PassVault\UserBundle\Entity\User
  profile:
     form:
        type: passvault_user_profile
