pass_vault_pass:
    resource: "@PassVaultPassBundle/Resources/config/routing.yml"
    prefix:   /

pass_vault_user:
    resource: "@PassVaultUserBundle/Resources/config/routing.yml"
    prefix:   /

entity_modal:
    resource: "@EntityModalBundle/Resources/config/routing.yml"
    prefix:   /
