security:
    encoders:
        PassVault\UserBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        passvault_provider:
            entity:
                class: PassVaultUserBundle:User
                property: email

    firewalls:
        secured_area:
            pattern: ^/
            form_login:
                check_path: /user/check
                login_path: /user/login
                provider: passvault_provider
                default_target_path: /
                require_previous_session: false
            logout:
                path:   /user/logout
                target: /
            anonymous: ~
