security:
    encoders:
        PassVault\UserBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        passvault_provider:
            entity:
                class: PassVaultUserBundle:User
                property: email

    firewalls:
        secured_area:
            pattern: ^/
            form_login:
                check_path: /sign/check
                login_path: /sign/in
                provider: passvault_provider
                require_previous_session: false
                always_use_default_target_path: false
                default_target_path: /
                target_path_parameter: _target_path
                use_referer: true
            logout:
                path:   /sign/out
                target: /
            anonymous: ~

    access_control:
        - { path: ^/sign/in, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/confirmation, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/forgot/password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/css, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/js, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/fonts, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }