#
# User Login
#
passvault_user_login:
    path: /sign/in
    defaults:
        _controller: PassVaultUserBundle:User:login

passvault_user_check:
    path: /sign/check

passvault_user_logout:
    path: /sign/out


#
# User Register
#

passvault_user_register:
    path: /register
    defaults:
        _controller: PassVaultUserBundle:User:register

passvault_user_confirmation:
    path: /confirmation/{token}
    defaults:
        _controller: PassVaultUserBundle:User:confirmation

passvault_user_forgotpassword:
    path: /forgot/password
    defaults:
        _controller: PassVaultUserBundle:User:forgotPassword

#
# Team
#

passvault_team_index:
    path: /team
    defaults:
        _controller: PassVaultUserBundle:Team:view

passvault_team_view:
    path: /team/view/{id}
    defaults:
        _controller: PassVaultUserBundle:Team:view

passvault_team_add:
    path: /team/add
    defaults:
        _controller: PassVaultUserBundle:Team:view

passvault_team_delete:
    path: /team/{id}/delete
    defaults:
        _controller: PassVaultUserBundle:Team:delete

passvault_team_add_user:
    path: /team/{id}/add/user
    defaults:
        _controller: PassVaultUserBundle:Team:invite
