passvault_user_login:
    path: /user/login
    defaults:
        _controller: PassVaultUserBundle:User:login

passvault_user_check:
    path: /user/check

passvault_user_logout:
    path: /user/logout

passvault_team_index:
    path: /team
    defaults:
        _controller: PassVaultUserBundle:Team:view

passvault_team_view:
    path: /team/view/{id}
    defaults:
        _controller: PassVaultUserBundle:Team:view

passvault_team_add:
    path: /team/add
    defaults:
        _controller: PassVaultUserBundle:Team:view

passvault_team_delete:
    path: /team/{id}/delete
    defaults:
        _controller: PassVaultUserBundle:Team:delete

passvault_team_add_user:
    path: /team/{id}/add/user
    defaults:
        _controller: PassVaultUserBundle:Team:invite
