services:

    pass_vault.security_voter.team_voter:
        class: PassVault\UserBundle\Security\Authorization\Voter\TeamVoter
        arguments:
            - @service_container
        tags:
            - { name: security.voter }

    passvault.form_type.team_type:
        class: PassVault\UserBundle\Form\Type\TeamType
        arguments:
            - @service_container
        tags:
            - { name: form.type, alias: team }

    passvault.form_type.teamuser_type:
        class: PassVault\UserBundle\Form\Type\TeamUserType
        arguments:
            - @service_container
        tags:
            - { name: form.type, alias: teamuser }