services:

    passvault.form_type.team_type:
        class: PassVault\UserBundle\Form\Type\TeamType
        arguments:
            - @service_container
        tags:
            - { name: form.type, alias: team }
