#
# Homepage
#

passvault_homepage:
    path:     /
    defaults: { _controller: PassVaultPassBundle:Node:View }

#
# Node
#

passvault_node_view:
    path:     /node/{id}/view
    defaults: { _controller: PassVaultPassBundle:Node:view }

passvault_node_add:
    path:     /node/add/vault
    defaults:
        _controller: PassVaultPassBundle:Node:add
        type: vault

passvault_node_add_to:
    path:     /node/{parent}/add/{type}
    defaults: { _controller: PassVaultPassBundle:Node:add }
    requirements:
        type:  folder|password

passvault_node_add_team:
    path:     /node/{id}/add/team
    defaults: { _controller: PassVaultPassBundle:Node:addTeam }

passvault_node_add_user:
    path:     /node/{id}/add/user
    defaults: { _controller: PassVaultPassBundle:Node:addUser }
