#
# Homepage
#

passvault_homepage:
    path:     /
    defaults: { _controller: PassVaultPassBundle:Node:View }

#
# Node
#

passvault_node_view:
    path:     /node/view/{id}
    defaults: { _controller: PassVaultPassBundle:Node:view }

passvault_node_add:
    path:     /node/add/{type}
    defaults: { _controller: PassVaultPassBundle:Node:add }

passvault_node_add_to:
    path:     /node/{parent}/add/{type}
    defaults: { _controller: PassVaultPassBundle:Node:add }